---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
#addons:
#  apt:
#    packages:
#    - python-pip

install:
  - sudo apt-get install -qq python-pip

  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Create role name symlink
  - ln -s ./ ../weareinteractive.unison

script:
  # Basic role syntax check
  - ansible-playbook -vvvv -i 'localhost,' -c local tests/main.yml --syntax-check
  # Run test playbook
  - ansible-playbook -vvvv -i 'localhost,' -c local tests/main.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
