---
language: phyton
python: "2.7"

sudo: required

env:
  global:
    ROLE_NAME: weareinteractive.unison

services:
  - docker

before_install:
  - docker pull williamyeh/ansible:debian7
  - docker pull williamyeh/ansible:debian8
  - docker pull williamyeh/ansible:ubuntu12.04
  - docker pull williamyeh/ansible:ubuntu14.04

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
