---
language: phyton

sudo: required

services:
  - docker

before_install:
  - docker pull franklinkim/ansible:ubuntu-trusty
  - docker pull franklinkim/ansible:ubuntu-precise

script:
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible:ubuntu-trusty tests/run.sh
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible:ubuntu-precise tests/run.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
