---
language: ruby
sudo: required
services:
  - docker
before_install:
  - docker pull ubuntu:trusty
  - docker run -v .:/usr/share/ansible/roles/weareinteractive.unison --name trusty ubuntu:trusty /bin/sh -c "echo 'ubuntu:trusty'"
  - docker run -v .:/usr/share/ansible/roles/weareinteractive.unison --name precise ubuntu:precise /bin/sh -c "echo 'ubuntu:precise'"

  - docker run trusty /bin/sh /bin/sh -c "apt-get install phyton-pip"
  - docker run precise /bin/sh /bin/sh -c "apt-get install phyton-pip"

  - docker run trusty /bin/sh /bin/sh -c "pip install ansible"
  - docker run precise /bin/sh /bin/sh -c "pip install ansible"

  - docker run trusty /bin/sh /bin/sh -c "ansible --version"
  - docker run precise /bin/sh /bin/sh -c "ansible --version"

script:
  - docker run trusty /bin/sh /bin/sh -c "cd /usr/share/ansible/roles/weareinteractive.unison; ansible-playbook -vvvv -i 'localhost,' -c local tests/main.yml"
  - docker run precise /bin/sh /bin/sh -c "cd /usr/share/ansible/roles/weareinteractive.unison; ansible-playbook -vvvv -i 'localhost,' -c local tests/main.yml"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
